// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"8lyy27f0z9","name":"sampleCloudApi","description":"","endpoint":"https://8lyy27f0z9.execute-api.eu-central-1.amazonaws.com/Development","region":"eu-central-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'eu-central-1:f9850de4-db58-40ef-9ba4-bd579c45f329',
    'aws_cognito_region': 'eu-central-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'fitnessfirstpleasewo-hosting-mobilehub-1311487274',
    'aws_content_delivery_bucket_region': 'eu-central-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dg27ecwjywidj.cloudfront.net',
    'aws_mobile_analytics_app_id': 'b153f9ef07664d709f9b356b831dc8cd',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3acfa6a2-02a8-4dcb-bd17-ff0dc744904f',
    'aws_project_name': 'Fitness-First-Please-Work',
    'aws_project_region': 'eu-central-1',
    'aws_resource_bucket_name': 'fitnessfirstpleasewo-deployments-mobilehub-1311487274',
    'aws_resource_name_prefix': 'fitnessfirstpleasewo-mobilehub-1311487274',
}

export default awsmobile;
