// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"e34v6b7cl4","name":"FitnessFirstApi","description":"this is our app API","endpoint":"https://e34v6b7cl4.execute-api.eu-central-1.amazonaws.com/Development","region":"eu-central-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'eu-central-1:7679fc9d-5b24-4706-bd1e-065b0db9ecba',
    'aws_cognito_region': 'eu-central-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactnativerepo-hosting-mobilehub-139217247',
    'aws_content_delivery_bucket_region': 'eu-central-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd15cmj9goma46s.cloudfront.net',
    'aws_mobile_analytics_app_id': '67ee70e38ce647a2ad73ad5318cc8e98',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a0bbfdb2-f6cf-475c-ad1a-fed6abb32d02',
    'aws_project_name': 'React-Native-Repo-2018-09-27-23-51-33',
    'aws_project_region': 'eu-central-1',
    'aws_resource_bucket_name': 'reactnativerepo-deployments-mobilehub-139217247',
    'aws_resource_name_prefix': 'reactnativerepo-mobilehub-139217247',
}

export default awsmobile;
